apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: voting-processor
  name: voting-processor
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: voting-processor
  type: NodePort
status:
  loadBalancer: {}
